### ISSUE TITLE
Getting EPIPE error code every few minutes

### ISSUE THREAD

**Issue by dushyantbangal** [aws/aws-iot-device-sdk-js#263]
I have multiple devices (RaspberryPi 3 B+) use the same code, **but I'm facing the issue only on one.**

Each device has a unique clientID and certificates.
Each device does 2 publishes every minute.
It runs for few minutes (sometimes hours), and then starts having connection issues.

I keep getting `EPIPE` error, I don't know if its in publish or connection error, I've added some more logs and will update the post.

It keeps getting connected and disconnected every few minutes, and keeps throwing that error.
It still sends data, but not all of it. 
Instead of publishing 2 payloads every minutes, its able to send 3 payloads in a minute, and then nothing for the next 1 or 2 minutes.

After I kill the restart the script, it sends all the data properly, and again after few hours, I start getting similar errors (I'm using `mqtt-level-store` for offline persistent storage)

**Normal Working:**
![image](https://user-images.githubusercontent.com/13764676/54026836-4a27dd00-41c5-11e9-8cda-5df944b29aa5.png)

**When I start receiving errors:**
![image](https://user-images.githubusercontent.com/13764676/54027178-90317080-41c6-11e9-8eb5-7dd0e01f14aa.png)

**Note:**
Both of these screenshots are for the same client. It starts behaving weird after some time.

**Comment by justinboswell** [comment]
We will definitely need some logs or more information to try to diagnose this. There's clearly a difference between the 2 clients. You already got the client IDs different, and I doubt it's policy related, but I assume you are using the same policy for the 2 devices?

**Comment by dushyantbangal** [comment]
@justinboswell yes, same policy.

**Comment by dushyantbangal** [comment]
**Update**
I have enabled different events from `device.on`, following are my logs:

```
Mar 12 15:34:14 : debug: Uploading...
Mar 12 15:34:14 : debug: Uploading...
Mar 12 15:34:14 : debug: packetsend
Mar 12 15:34:14 : debug: packetsend
Mar 12 15:34:17 : debug: Uploading...
Mar 12 15:34:17 : debug: packetsend
Mar 12 15:35:15 : debug: Uploading...
Mar 12 15:35:15 : debug: packetsend
Mar 12 15:35:17 : debug: Uploading...
Mar 12 15:35:17 : debug: packetsend
Mar 12 15:35:27 : error: offline
Mar 12 15:35:27 : error: undefined
Mar 12 15:35:27 : undefined
Mar 12 15:35:27 : error: undefined {"code":"EINVAL","errno":"EINVAL","syscall":"read"}
Mar 12 15:35:27 : { Error: read EINVAL
Mar 12 15:35:27 :     at _errnoException (util.js:992:11)
Mar 12 15:35:27 :     at TLSWrap.onread (net.js:618:25)
Mar 12 15:35:27 :   code: 'EINVAL',
Mar 12 15:35:27 :   errno: 'EINVAL',
Mar 12 15:35:27 :   syscall: 'read',
Mar 12 15:35:27 :   level: 'error',
Mar 12 15:35:27 :   [Symbol(level)]: 'error',
Mar 12 15:35:27 :   [Symbol(message)]: '{"code":"EINVAL","errno":"EINVAL","syscall":"read","level":"error"}' }
Mar 12 15:35:27 : error: close
Mar 12 15:35:27 : error: undefined
Mar 12 15:35:27 : undefined
Mar 12 15:35:28 : debug: reconnect
Mar 12 15:35:28 : debug: packetsend
Mar 12 15:35:29 : info: AWS Connected
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:29 : debug: packetsend
Mar 12 15:35:30 : error: offline
Mar 12 15:35:30 : error: undefined
Mar 12 15:35:30 : undefined
Mar 12 15:35:30 : error: close
Mar 12 15:35:30 : error: undefined
Mar 12 15:35:30 : undefined
Mar 12 15:35:32 : debug: reconnect
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : info: AWS Connected
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:32 : debug: packetsend
Mar 12 15:35:33 : debug: packetsend
Mar 12 15:35:33 : debug: packetsend
Mar 12 15:35:33 : debug: packetsend
Mar 12 15:35:33 : error: offline
Mar 12 15:35:33 : error: undefined
Mar 12 15:35:33 : undefined
Mar 12 15:35:33 : error: close
Mar 12 15:35:33 : error: undefined
Mar 12 15:35:33 : undefined
Mar 12 15:35:37 : debug: reconnect
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : info: AWS Connected
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:37 : debug: packetsend
Mar 12 15:35:38 : debug: packetsend
Mar 12 15:35:38 : debug: packetsend
Mar 12 15:35:38 : debug: packetsend
Mar 12 15:35:38 : debug: packetsend
Mar 12 15:35:38 : debug: packetsend
Mar 12 15:35:38 : error: offline
Mar 12 15:35:38 : error: undefined
Mar 12 15:35:38 : undefined
Mar 12 15:35:38 : error: close
Mar 12 15:35:38 : error: undefined
Mar 12 15:35:38 : undefined
Mar 12 15:35:46 : debug: reconnect
Mar 12 15:35:46 : debug: packetsend
Mar 12 15:35:46 : info: AWS Connected

```

`Uploading...` is when I do a publish.
When the issue starts, the `offline` event is emitted, with no object in callback (printed `undefined`)

Then I get the `EINVAL` error, I believe that happens in the `error` event.

Then `close` is emitted, with with no object in callback (printed `undefined`)

Then `reconnect`, followed by `connect` event
Again, in a second, after a few `packetsend` (dont think all of them reach), it hits `offline` and the same cycle starts.

Every now and then I get this:

```

Mar 12 16:12:10 : debug: packetsend
Mar 12 16:12:10 : debug: packetsend
Mar 12 16:12:10 : error: offline
Mar 12 16:12:10 : error: undefined
Mar 12 16:12:10 : undefined
Mar 12 16:12:10 : error: undefined {"code":"EPIPE"}
Mar 12 16:12:10 : { Error: This socket has been ended by the other party
Mar 12 16:12:10 :     at TLSSocket.writeAfterFIN [as write] (net.js:364:12)
Mar 12 16:12:10 :     at subscribe (/path/node_modules/mqtt-packet/writeToStream.js:364:10)
Mar 12 16:12:10 :     at Object.generate [as writeToStream] (/path/node_modules/mqtt-packet/writeToStream.js:41:14)
Mar 12 16:12:10 :     at sendPacket (/path/node_modules/mqtt/lib/client.js:37:27)
Mar 12 16:12:10 :     at MqttClient._sendPacket (/path/node_modules/mqtt/lib/client.js:776:5)
Mar 12 16:12:10 :     at MqttClient.subscribe (/path/node_modules/mqtt/lib/client.js:523:8)
Mar 12 16:12:10 :     at Timeout._drainOperationQueue [as _onTimeout] (/path/node_modules/aws-iot-device-sdk/device/index.js:701:20)
Mar 12 16:12:10 :     at ontimeout (timers.js:498:11)
Mar 12 16:12:10 :     at tryOnTimeout (timers.js:323:5)
Mar 12 16:12:10 :     at Timer.listOnTimeout (timers.js:290:5)
Mar 12 16:12:10 :   code: 'EPIPE',
Mar 12 16:12:10 :   level: 'error',
Mar 12 16:12:10 :   [Symbol(level)]: 'error',
Mar 12 16:12:10 :   [Symbol(message)]: '{"code":"EPIPE","level":"error"}' }
Mar 12 16:12:10 : error: close
Mar 12 16:12:10 : error: undefined
Mar 12 16:12:10 : undefined
```

**Comment by justinboswell** [comment]
The ```Error: This socket has been ended by the other party``` is an indicator that the service hung up on you, which means it didn't like the last thing you sent. Was it an overly large message, a pub/sub with QoS 2, or did you send [too many publishes/sec](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) (I can't tell because this is a snipped log)?

**Comment by dushyantbangal** [comment]
@justinboswell everything is `qos:1`, and the payload is hardly 10KB.
And like I said, once I restart it, I starts sending all the backlogged data (which is a larger number than live data), and that happens successfully. 
If the payload was the issue here, it would keep getting rejected (has happened to me before when I published message larger than 128 KB.

The backlogged data is easily 500+ publishes. The live data is 2 pubs per minute.

I'll update my previous comment with a bigger log before `EPIPE`

**Comment by justinboswell** [comment]
I'm trying to narrow in on why the service might hang up on you.

* Are the publishes going to custom topics, or are they Jobs or Shadow service topics? 
* Are the topics or publishes in violation of any [service limits](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot)?
  * I can't tell because I don't know what your messages actually are. The publish rate looks ok in the log above.
* Are other clients connected at the same time this happens? If so, could the total connected mesh exceed any of the service limits (check the per-account limits)?

Is there any reason why the automatic reconnect isn't taking care of this? What necessitates a restart as the recovery mechanism?

**Comment by dushyantbangal** [comment]
@justinboswell 

> Are the publishes going to custom topics, or are they Jobs or Shadow service topics?

all publishes are to custom topics.


> Are the topics or publishes in violation of any service limits?

The message is a stringified JSON object, the length should be easily less that 150 characters.
Also, if this was the issue, restarting script wouldn't have worked, the messages would still get rejected.

> Are other clients connected at the same time this happens? If so, could the total connected mesh exceed any of the service limits (check the per-account limits)?

There are around 20-25 clients configured on my account, only this one has the issue.
The clients I configured after this one, are also working fine, so I don't think I'm crossing any service limit.
If this was the issue, I would face it randomly on other clients as well, right?

> Is there any reason why the automatic reconnect isn't taking care of this? What necessitates a restart as the recovery mechanism?

I'm wondering the same thing.

**Comment by dushyantbangal** [comment]
Now I think I should just delete this thing, and create it again.

**Comment by justinboswell** [comment]
That's a valid thing to try, though I wonder what is different about this problem device given that you have plenty of others that work just fine. This doesn't seem like an SDK issue from what I'm seeing, you may need to engage AWS support to troubleshoot why the service is hanging up if re-making the Thing doesn't solve your issue.

**Comment by Craigson** [comment]
@dushyantbangal I'm having a similar issue:

```
 26.07.19 14:10:28 (-0400)  server  ERROR { Error: This socket has been ended by the other party
26.07.19 14:10:28 (-0400)  server      at TLSSocket.writeAfterFIN [as write] (net.js:395:12)
26.07.19 14:10:28 (-0400)  server      at emptyPacket (/app/node_modules/mqtt-packet/writeToStream.js:477:17)
26.07.19 14:10:28 (-0400)  server      at Object.generate [as writeToStream] (/app/node_modules/mqtt-packet/writeToStream.js:49:14)
26.07.19 14:10:28 (-0400)  server      at sendPacket (/app/node_modules/mqtt/lib/client.js:37:27)
26.07.19 14:10:28 (-0400)  server      at MqttClient._sendPacket (/app/node_modules/mqtt/lib/client.js:776:5)
26.07.19 14:10:28 (-0400)  server      at MqttClient._checkPing (/app/node_modules/mqtt/lib/client.js:832:10)
26.07.19 14:10:28 (-0400)  server      at Timeout.<anonymous> (/app/node_modules/mqtt/lib/client.js:809:12)
26.07.19 14:10:28 (-0400)  server      at ontimeout (timers.js:438:13)
26.07.19 14:10:28 (-0400)  server      at tryOnTimeout (timers.js:300:5)
26.07.19 14:10:28 (-0400)  server      at listOnTimeout (timers.js:263:5) code: 'EPIPE' }
29.07.19 10:17:04 (-0400)  server  ERROR { Error: This socket has been ended by the other party
29.07.19 10:17:04 (-0400)  server      at TLSSocket.writeAfterFIN [as write] (net.js:395:12)
29.07.19 10:17:04 (-0400)  server      at emptyPacket (/app/node_modules/mqtt-packet/writeToStream.js:477:17)
29.07.19 10:17:04 (-0400)  server      at Object.generate [as writeToStream] (/app/node_modules/mqtt-packet/writeToStream.js:49:14)
29.07.19 10:17:04 (-0400)  server      at sendPacket (/app/node_modules/mqtt/lib/client.js:37:27)
29.07.19 10:17:04 (-0400)  server      at MqttClient._sendPacket (/app/node_modules/mqtt/lib/client.js:776:5)
29.07.19 10:17:04 (-0400)  server      at MqttClient._checkPing (/app/node_modules/mqtt/lib/client.js:832:10)
29.07.19 10:17:04 (-0400)  server      at Timeout.<anonymous> (/app/node_modules/mqtt/lib/client.js:809:12)
29.07.19 10:17:04 (-0400)  server      at ontimeout (timers.js:438:13)
29.07.19 10:17:04 (-0400)  server      at tryOnTimeout (timers.js:300:5)
29.07.19 10:17:04 (-0400)  server      at listOnTimeout (timers.js:263:5) code: 'EPIPE' }
```

Do you find any cause/resolution for your problem?

Out of interest, are you using a `Thing` or a `ThingShadow`?

**Comment by justinboswell** [comment]
Closing due to no comment from the requester in 4 months.

**Comment by Craigson** [comment]
@justinboswell are there other issues relating to this?

**Comment by justinboswell** [comment]
@Craigson none that we're aware of currently. The issue above does not appear SDK related; given the info available to troubleshoot, it's likely the requester would need to engage AWS support and look at traces from the service end to troubleshoot further.

**Comment by dod91** [comment]
@dushyantbangal same issue here (even after creating a new thing), did you find a solution on this?
